// Mapping of audio file names to static require calls
export const audioAssets: { [key: string]: any } = {
  // HydStops audio files
  '1.Choutuppal.mp3': require('../assets/audio/HydStops/1.Choutuppal.mp3'),
  '2.ramojifilmcity1.mp3': require('../assets/audio/HydStops/2.ramojifilmcity1.mp3'),
  '3.hayathnagar.mp3': require('../assets/audio/HydStops/3.hayathnagar.mp3'),
  '4.Vanasthalipuram.mp3': require('../assets/audio/HydStops/4.Vanasthalipuram.mp3'),
  '5.LBnagar.mp3': require('../assets/audio/HydStops/5.LBnagar.mp3'),
  '6.kothapeta.mp3': require('../assets/audio/HydStops/6.kothapeta.mp3'),
  '7.dilsuknagar.mp3': require('../assets/audio/HydStops/7.dilsuknagar.mp3'),
  '8.chaithanyapuri.mp3': require('../assets/audio/HydStops/8.chaithanyapuri.mp3'),
  '9.TVTOWERMALAKPET.mp3': require('../assets/audio/HydStops/9.TVTOWERMALAKPET.mp3'),
  '10.koti.mp3': require('../assets/audio/HydStops/10.koti.mp3'),
  '11.abids.mp3': require('../assets/audio/HydStops/11.abids.mp3'),
  '12.nampally.mp3': require('../assets/audio/HydStops/12.nampally.mp3'),
  '13.lakdikapool.mp3': require('../assets/audio/HydStops/13.lakdikapool.mp3'),
  '14.khairathabad.mp3': require('../assets/audio/HydStops/14.khairathabad.mp3'),
  '15.panjaguta.mp3': require('../assets/audio/HydStops/15.panjaguta.mp3'),
  '16.ameerpet.mp3': require('../assets/audio/HydStops/16.ameerpet.mp3'),
  '17.srnagar.mp3': require('../assets/audio/HydStops/17.srnagar.mp3'),
  '18.ESI.mp3': require('../assets/audio/HydStops/18.ESI.mp3'),
  '19.erragada.mp3': require('../assets/audio/HydStops/19.erragada.mp3'),
  '20.bharthnaagar.mp3': require('../assets/audio/HydStops/20.bharthnaagar.mp3'),
  '21.moosapet.mp3': require('../assets/audio/HydStops/21.moosapet.mp3'),
  '22.kukatpally.mp3': require('../assets/audio/HydStops/22.kukatpally.mp3'),
  '23.vivekanandanagar.mp3': require('../assets/audio/HydStops/23.vivekanandanagar.mp3'),
  '24.kphb.mp3': require('../assets/audio/HydStops/24.kphb.mp3'),
  '25.jntu.mp3': require('../assets/audio/HydStops/25.jntu.mp3'),
  '26.nizampet.mp3': require('../assets/audio/HydStops/26.nizampet.mp3'),
  '27.hydernagar.mp3': require('../assets/audio/HydStops/27.hydernagar.mp3'),
  '28.miyapur.mp3': require('../assets/audio/HydStops/28.miyapur.mp3'),
  '29.miyapurallwynXroad.mp3': require('../assets/audio/HydStops/29.miyapurallwynXroad.mp3'),
  '30.madinaguda.mp3': require('../assets/audio/HydStops/30.madinaguda.mp3'),
  '31.gangaram.mp3': require('../assets/audio/HydStops/31.gangaram.mp3'),
  '32.chandanagar.mp3': require('../assets/audio/HydStops/32.chandanagar.mp3'),
  '33.lingampally.mp3': require('../assets/audio/HydStops/33.lingampally.mp3'),
  '34.bhel.mp3': require('../assets/audio/HydStops/34.bhel.mp3'),
  '35.Ayyappasocity.mp3': require('../assets/audio/HydStops/35.Ayyappasocity.mp3'),
  '36.Madhapur.mp3': require('../assets/audio/HydStops/36.Madhapur.mp3'),
  '37.Hitechcity.mp3': require('../assets/audio/HydStops/37.Hitechcity.mp3'),
  '38.Biodiversity.mp3': require('../assets/audio/HydStops/38.Biodiversity.mp3'),
  '39.Gachibowli.mp3': require('../assets/audio/HydStops/39.Gachibowli.mp3'),
  '40.Kondapur.mp3': require('../assets/audio/HydStops/40.Kondapur.mp3'),
  '41.Kothaguda.mp3': require('../assets/audio/HydStops/41.Kothaguda.mp3'),

  // VizagStops audio files
  '1.Gajuwaka.mp3': require('../assets/audio/VizagStops/1.Gajuwaka.mp3'),
  '2.NAD Jn.mp3': require('../assets/audio/VizagStops/2.NAD Jn.mp3'),
  '3.Kurmanapalem.mp3': require('../assets/audio/VizagStops/3.Kurmanapalem.mp3'),
  '4.Airport Gate.mp3': require('../assets/audio/VizagStops/4.Airport Gate.mp3'),
  '5.Maddilapalem.mp3': require('../assets/audio/VizagStops/5.Maddilapalem.mp3'),
  '6.Isukathota.mp3': require('../assets/audio/VizagStops/6.Isukathota.mp3'),
  '7.Akkayapalem.mp3': require('../assets/audio/VizagStops/7.Akkayapalem.mp3'),
  '8.MVP Colony.mp3': require('../assets/audio/VizagStops/8.MVP Colony.mp3'),
  '9.Ramatalkies.mp3': require('../assets/audio/VizagStops/9.Ramatalkies.mp3'),
  '10.Srinagar.mp3': require('../assets/audio/VizagStops/10.Srinagar.mp3'),
  '11.Sheelanagar.mp3': require('../assets/audio/VizagStops/11.Sheelanagar.mp3'),
  '12.Murali Nagar.mp3': require('../assets/audio/VizagStops/12.Murali Nagar.mp3'),
  '13.Kakani Nagar.mp3': require('../assets/audio/VizagStops/13.Kakani Nagar.mp3'),
  '14.Lankelapalem.mp3': require('../assets/audio/VizagStops/14.Lankelapalem.mp3'),
  '15.Aganampudi.mp3': require('../assets/audio/VizagStops/15.Aganampudi.mp3'),
  '16.BHPV Junctiom.mp3': require('../assets/audio/VizagStops/16.BHPV Junctiom.mp3'),
  '17.Gurudwara.mp3': require('../assets/audio/VizagStops/17.Gurudwara.mp3'),
  '18.Urvasi.mp3': require('../assets/audio/VizagStops/18.Urvasi.mp3'),

  // RjyStops audio files
  '1.Bommuru.mp3': require('../assets/audio/RjyStops/1.Bommuru.mp3'),
  '2.diwancheruvu.mp3': require('../assets/audio/RjyStops/2.diwancheruvu.mp3'),
  '3.gokavaram buststand.mp3': require('../assets/audio/RjyStops/3.gokavaram buststand.mp3'),
  '4.kambala cheruvu.mp3': require('../assets/audio/RjyStops/4.kambala cheruvu.mp3'),
  '5.Katheru.mp3': require('../assets/audio/RjyStops/5.Katheru.mp3'),
  '6.Lalacheruvu.mp3': require('../assets/audio/RjyStops/6.Lalacheruvu.mp3'),
  '7.Morampudi.mp3': require('../assets/audio/RjyStops/7.Morampudi.mp3'),
  '8.papermill road.mp3': require('../assets/audio/RjyStops/8.papermill road.mp3'),
  '9.Vemagiri.mp3': require('../assets/audio/RjyStops/9.Vemagiri.mp3'),

  // KKDStops audio files
  '1.Balaji Cheruvu.mp3': require('../assets/audio/KKDStops/1.Balaji Cheruvu.mp3'),
  '2.Indrapalem.mp3': require('../assets/audio/KKDStops/2.Indrapalem.mp3'),
  '3.Madhavapatnam.mp3': require('../assets/audio/KKDStops/3.Madhavapatnam.mp3'),
  '4.Prathap Nagar.mp3': require('../assets/audio/KKDStops/4.Prathap Nagar.mp3'),
  '5.PRdegree college.mp3': require('../assets/audio/KKDStops/5.PRdegree college.mp3'),

  // ST-12 audio files
  '3telaprolu.mp3': require('../assets/audio/ST-12/3telaprolu.mp3'),
  '4veeravali.mp3': require('../assets/audio/ST-12/4veeravali.mp3'),
  '5Hanumanjunction.mp3': require('../assets/audio/ST-12/5Hanumanjunction.mp3'),
  '6chebrolu.mp3': require('../assets/audio/ST-12/6chebrolu.mp3'),
  '7eluru.mp3': require('../assets/audio/ST-12/7eluru.mp3'),
  '8denduluru.mp3': require('../assets/audio/ST-12/8denduluru.mp3'),
  '9gundugolunu.mp3': require('../assets/audio/ST-12/9gundugolunu.mp3'),
  '10bhimadolu.mp3': require('../assets/audio/ST-12/10bhimadolu.mp3'),
  '11kurrelagudem.mp3': require('../assets/audio/ST-12/11kurrelagudem.mp3'),
  '12pulla.mp3': require('../assets/audio/ST-12/12pulla.mp3'),
  '13kaikaram.mp3': require('../assets/audio/ST-12/13kaikaram.mp3'),
  '14narayanapuram.mp3': require('../assets/audio/ST-12/14narayanapuram.mp3'),
  '15unguturu.mp3': require('../assets/audio/ST-12/15unguturu.mp3'),
  '16tpgudem.mp3': require('../assets/audio/ST-12/16tpgudem.mp3'),
  '17duva.mp3': require('../assets/audio/ST-12/17duva.mp3'),
  '18tanuku.mp3': require('../assets/audio/ST-12/18tanuku.mp3'),
  '19peravali.mp3': require('../assets/audio/ST-12/19peravali.mp3'),
  '20annavarapadu.mp3': require('../assets/audio/ST-12/20annavarapadu.mp3'),
  '21sidhantham.mp3': require('../assets/audio/ST-12/21sidhantham.mp3'),
  '22ethakota.mp3': require('../assets/audio/ST-12/22ethakota.mp3'),
  '23ravulapalem.mp3': require('../assets/audio/ST-12/23ravulapalem.mp3'),
  '24jonnada.mp3': require('../assets/audio/ST-12/24jonnada.mp3'),
  '25alamuru.mp3': require('../assets/audio/ST-12/25alamuru.mp3'),
  '26kothuru.mp3': require('../assets/audio/ST-12/26kothuru.mp3'),
  '27mandapeta.mp3': require('../assets/audio/ST-12/27mandapeta.mp3'),
  '28Machavaram.mp3': require('../assets/audio/ST-12/28Machavaram.mp3'),
  '29Ramachandrapuram.mp3': require('../assets/audio/ST-12/29Ramachandrapuram.mp3'),
  '30draksharamam.mp3': require('../assets/audio/ST-12/30draksharamam.mp3'),
  '31gollapalem.mp3': require('../assets/audio/ST-12/31gollapalem.mp3'),
  '32kakinada.mp3': require('../assets/audio/ST-12/32kakinada.mp3'),

  // ST-122 audio files
  '30velangi.mp3': require('../assets/audio/ST-A02/30velangi.mp3'),
  '31karapa.mp3': require('../assets/audio/ST-A02/31karapa.mp3'),

  // ST-A04 audio files
  '9gundugolanu.mp3': require('../assets/audio/ST-A04/9gundugolanu.mp3'),
  '10denduluru.mp3': require('../assets/audio/ST-A04/10denduluru.mp3'),
  '11bhimadolu.mp3': require('../assets/audio/ST-A04/11bhimadolu.mp3'),
  '12dobacherla.mp3': require('../assets/audio/ST-A04/12dobacherla.mp3'),
  '13nallajerla.mp3': require('../assets/audio/ST-A04/13nallajerla.mp3'),
  '14ananthapalli.mp3': require('../assets/audio/ST-A04/14ananthapalli.mp3'),
  '15yerrannagudem.mp3': require('../assets/audio/ST-A04/15yerrannagudem.mp3'),
  '16devarapalli.mp3': require('../assets/audio/ST-A04/16devarapalli.mp3'),
  '17dudhukuru.mp3': require('../assets/audio/ST-A04/17dudhukuru.mp3'),
  '18gowripatnam.mp3': require('../assets/audio/ST-A04/18gowripatnam.mp3'),
  '19pangidi.mp3': require('../assets/audio/ST-A04/19pangidi.mp3'),
  '20kovuru.mp3': require('../assets/audio/ST-A04/20kovuru.mp3'),
  '21rajahmundry.mp3': require('../assets/audio/ST-A04/21rajahmundry.mp3'),
  '22rajanagaram.mp3': require('../assets/audio/ST-A04/22rajanagaram.mp3'),
  '23Vadisaleru.mp3': require('../assets/audio/ST-A04/23Vadisaleru.mp3'),
  '24Surampalem.mp3': require('../assets/audio/ST-A04/24Surampalem.mp3'),
  '24Rangampeta.mp3': require('../assets/audio/ST-A04/24Rangampeta.mp3'),
  '26Peddapuram.mp3': require('../assets/audio/ST-A04/26Peddapuram.mp3'),
  '27Samarlakota.mp3': require('../assets/audio/ST-A04/27Samarlakota.mp3'),
  '28kakinada.mp3': require('../assets/audio/ST-A04/28kakinada.mp3'),

  // ST-A06 audio files
  '3Hanumanjunction.mp3': require('../assets/audio/ST-A06/3Hanumanjunction.mp3'),
  '4eluru.mp3': require('../assets/audio/ST-A06/4eluru.mp3'),
  '5gundugolunu.mp3': require('../assets/audio/ST-A06/5gundugolunu.mp3'),
  '6denduluru.mp3': require('../assets/audio/ST-A06/6denduluru.mp3'),
  '7bhimadolu.mp3': require('../assets/audio/ST-A06/7bhimadolu.mp3'),
  '8dobacherla.mp3': require('../assets/audio/ST-A06/8dobacherla.mp3'),
  '9nallajerla.mp3': require('../assets/audio/ST-A06/9nallajerla.mp3'),
  '10ananthapalli.mp3': require('../assets/audio/ST-A06/10ananthapalli.mp3'),
  '11yerrannagudem.mp3': require('../assets/audio/ST-A06/11yerrannagudem.mp3'),
  '12devarapali.mp3': require('../assets/audio/ST-A06/12devarapali.mp3'),
  '13dudhukuru.mp3': require('../assets/audio/ST-A06/13dudhukuru.mp3'),
  '14gowripatnam.mp3': require('../assets/audio/ST-A06/14gowripatnam.mp3'),
  '15pangidi.mp3': require('../assets/audio/ST-A06/15pangidi.mp3'),
  '16kovuru.mp3': require('../assets/audio/ST-A06/16kovuru.mp3'),
  '17rajahmundry.mp3': require('../assets/audio/ST-A06/17rajahmundry.mp3'),
  '18vemagiri.mp3': require('../assets/audio/ST-A06/18vemagiri.mp3'),
  '19kadiyam.mp3': require('../assets/audio/ST-A06/19kadiyam.mp3'),
  '20kesavaram.mp3': require('../assets/audio/ST-A06/20kesavaram.mp3'),
  '21dwarapudi.mp3': require('../assets/audio/ST-A06/21dwarapudi.mp3'),
  '22anaparthi.mp3': require('../assets/audio/ST-A06/22anaparthi.mp3'),
  '23balabadrapuram.mp3': require('../assets/audio/ST-A06/23balabadrapuram.mp3'),
  '24bikkavolu.mp3': require('../assets/audio/ST-A06/24bikkavolu.mp3'),
  '25peddabrahmadevam.mp3': require('../assets/audio/ST-A06/25peddabrahmadevam.mp3'),
  '26medapadu.mp3': require('../assets/audio/ST-A06/26medapadu.mp3'),
  '27veltlapalem.mp3': require('../assets/audio/ST-A06/27veltlapalem.mp3'),
  '28samrlakota.mp3': require('../assets/audio/ST-A06/28samrlakota.mp3'),
  '29kakinada.mp3': require('../assets/audio/ST-A06/29kakinada.mp3'),

  // ST-VH02 audio files
  '1vijayawada.mp3': require('../assets/audio/ST-VH02/1vijayawada.mp3'),
  '2gannavaram.mp3': require('../assets/audio/ST-VH02/2gannavaram.mp3'),
  '16devarapali.mp3': require('../assets/audio/ST-VH02/16devarapali.mp3'),
  '23gandepalli.mp3': require('../assets/audio/ST-VH02/23gandepally.mp3'),
  '24jaggampetta.mp3': require('../assets/audio/ST-VH02/24jaggampetta.mp3'),
  '25yerravaram.mp3': require('../assets/audio/ST-VH02/25yerravaram.mp3'),
  '26prathipadu.mp3': require('../assets/audio/ST-VH02/26prathipadu.mp3'),
  '27kattipudi.mp3': require('../assets/audio/ST-VH02/27kattipudi.mp3'),
  '28annavaram.mp3': require('../assets/audio/ST-VH02/28annavaram.mp3'),
  '29tuni.mp3': require('../assets/audio/ST-VH02/29tuni.mp3'),
  '30nakkapli.mp3': require('../assets/audio/ST-VH02/30nakkapli.mp3'),
  '31adda road.mp3': require('../assets/audio/ST-VH02/31adda road.mp3'),
  '32yelamanchili.mp3': require('../assets/audio/ST-VH02/32yelamanchili.mp3'),
  '33anakapali.mp3': require('../assets/audio/ST-VH02/33anakapali.mp3'),
  '34Visakhapatnam.mp3': require('../assets/audio/ST-VH02/34Visakhapatnam.mp3'),

  //Quick Actions files
  'WashroomBreak.mp3': require('../assets/audio/QA/WashroomBreak.mp3'),
  'DinnerBreak.mp3': require('../assets/audio/QA/DinnerBreak.mp3'),

  //Welcome Notes audio files
  'NL02 B 0492 - Samanvi_Travels_Safety_Announcement..mp3': require('../assets/audio/welcomenotes/NL02 B 0492 - Samanvi_Travels_Safety_Announcement..mp3'),
  'NL02 B 0493 - Samanvi_Travels_Safety_Announcement..mp3': require('../assets/audio/welcomenotes/NL02 B 0493 - Samanvi_Travels_Safety_Announcement..mp3'),
  'NL02 B 3152 - Samanvi_Travels_Safety_Announcement..mp3': require('../assets/audio/welcomenotes/NL02 B 3152 - Samanvi_Travels_Safety_Announcement..mp3'),
  'NL02 B 3153 - Samanvi_Travels_Safety_Announcement..mp3': require('../assets/audio/welcomenotes/NL02 B 3153 - Samanvi_Travels_Safety_Announcement..mp3'),
  'NL02 B 4142 - Samanvi_Travels_Safety_Announcement..mp3': require('../assets/audio/welcomenotes/NL02 B 4142 - Samanvi_Travels_Safety_Announcement..mp3'),
  'NL02 B 4241 - Samanvi_Travels_Safety_Announcement..mp3': require('../assets/audio/welcomenotes/NL02 B 4241 - Samanvi_Travels_Safety_Announcement..mp3'),
  'NL02 B 5152 - Samanvi_Travels_Safety_Announcement..mp3': require('../assets/audio/welcomenotes/NL02 B 5152 - Samanvi_Travels_Safety_Announcement..mp3'),
  'NL02 B 5251 - Samanvi_Travels_Safety_Announcement..mp3': require('../assets/audio/welcomenotes/NL02 B 5251 - Samanvi_Travels_Safety_Announcement..mp3'),
  'NL02 B 6162 - Samanvi_Travels_Safety_Announcement..mp3': require('../assets/audio/welcomenotes/NL02 B 6162 - Samanvi_Travels_Safety_Announcement.mp3'),
  'NL02 B 6261 - Samanvi_Travels_Safety_Announcement..mp3': require('../assets/audio/welcomenotes/NL02 B 6261 - Samanvi_Travels_Safety_Announcement.mp3')
}; 